#!/usr/bin/env node
/** Bundles schema.sql into a TypeScript string so it is available at runtime. */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sql = readFileSync(join(root, 'src/lib/schema.sql'), 'utf8');

writeFileSync(
  join(root, 'src/lib/schemaSql.ts'),
  `// Generated by scripts/embed-schema.mjs — do not edit by hand.\nexport const SCHEMA_SQL = ${JSON.stringify(sql)};\n`
);
console.log('  Schema embedded.');
